# NumPy: Numerical Python
50-100x faster than lists.  Consumes less memory

**NumPy array creation**

In [1]:
import numpy as np

In [2]:
temperature=np.array([33.4,36.8,32.6,36.6,34.6,39.4])
average=np.mean(temperature)
average

np.float64(35.56666666666666)

In [3]:
 # One-dimensional array
numbers=np.array([10,14,20,30])
numbers

array([10, 14, 20, 30])

In [4]:
 # Two-dimensional array  (rows and columns)
values=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
 # Multi-dimensional array   (stack of multiple 2d arrays)
matrix=np.array([[[2,4,6],
                 [8,10,12]],
                [[14,16,18],
                 [20,22,24]]])
matrix

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

**Default values in an array**

In [6]:
# np.zeros(length)   fills array with 0
z_array=np.zeros(5)
z_array

array([0., 0., 0., 0., 0.])

In [7]:
# np.ones(length) fills array with 1
o_array=np.ones(3)
o_array

array([1., 1., 1.])

In [8]:
# np.full(length),specific val     fills array with specific value
ar=np.full((3),7)
ar

array([7, 7, 7])

In [9]:
#Making 2d-array with zeros  rows and columns frmt
z2d_array=np.zeros((2,4)) 
z2d_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#Making 2d-array with ones
o2d_array=np.ones((3,5))
o2d_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#Making 2d-array with full
f_array=np.full((3,5),8)
f_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

# Creating sequences of numbers

In [13]:
# arange() function workd like range()
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# Creating Identity Matrix (1's on diagonal)

In [15]:
im=np.eye(4)
im

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])