# Indexing and Slicing

In [43]:
import numpy as np

 **Indexing**
 array[index]            1d-array
 array[row,column]       2d-array 

In [44]:
arr=np.array([10,20,30,40,50])
# arr[0]
# arr[1]
# arr[3]
arr[-1]

np.int64(50)

**Slicing**    Start:Stop:Step

In [45]:
# array[start:end]  start to end - 1
a=np.array([3,6,4,8,6,9,1])
# a[:]
# a[:4]
# a[0:3]
# a[1:5]
a[1:-1]

array([6, 4, 8, 6, 9])

In [46]:
a=np.array([3,6,4,8,6,9,1,5,13,12,18,16])
# a[:-1:2]
# a[1:-1:2]
a[::3]

array([ 3,  8,  1, 12])

In [47]:
# Negative step: reverse 
a=np.array([3,6,4,8,6,9,1,5,13,12,18,16])
a[::-1]

array([16, 18, 12, 13,  5,  1,  9,  6,  8,  4,  6,  3])

**Fancy Indexing**  Selecting multiple elements at once

In [48]:
a=np.array([3,6,4,8,6,9,1,5,13,12,18,16])
a[[1,4,7]]

array([6, 6, 5])

**Filtering Data (filtering based on condition)**
Mostly used in ML

In [49]:
 a=np.array([3,6,4,8,6,9,1,5,13,12,18,16])
# a[a<5]
a[a>10]

array([13, 12, 18, 16])