**Reshaping: Changing dimensions without modifying the data**

In [2]:
import numpy as np

In [12]:
# 1d to 2d
# reshape(rows , columns)  specify new shape
# Reshape will work only if the dimensions match
# rows × columns = total elements in array
array=np.array([10,30,50,70,90,110])
# new_arr=array.reshape(2,3)
new_arr=array.reshape(6,1)
new_arr

array([[ 10],
       [ 30],
       [ 50],
       [ 70],
       [ 90],
       [110]])

In [14]:
# 1d to 3d
array=np.array([10,30,50,70,90,110])
new=array.reshape(2,3,1)
new

array([[[ 10],
        [ 30],
        [ 50]],

       [[ 70],
        [ 90],
        [110]]])

In [16]:
array=np.array([10,30,50,70,90,110,22,54,14,76])
new=array.reshape(2,5,1)
new

array([[[ 10],
        [ 30],
        [ 50],
        [ 70],
        [ 90]],

       [[110],
        [ 22],
        [ 54],
        [ 14],
        [ 76]]])