# Modifying an array

In [2]:
import numpy as np

In [ ]:
# np.insert(array, index, value)
# array        → the array in which you want to insert
# index        → the position where you want to insert
# value        → the value(s) you want to insert
# axis         → if None: the array is first flattened to 1D and a new copy is returned
# axis=0,        row-wise
# axis=1,        column-wise

In [25]:
#  In 1d
arr=np.array([1,3,4,5,6])
new=np.insert(arr,1,2)
new

array([1, 2, 3, 4, 5, 6])

In [26]:
# In 2d
array=np.array([[10,30],
               [40,50]])
new_array=np.insert(array,1,[100,200], axis =0)
new_array
# inserted in 2nd row

array([[ 10,  30],
       [100, 200],
       [ 40,  50]])

In [27]:
# In 2d
array=np.array([[10,30],
               [40,50]])
new_array=np.insert(array,1,[100,200], axis =1)
new_array
# inserted in 2nd column

array([[ 10, 100,  30],
       [ 40, 200,  50]])

In [28]:
# In 2d
array=np.array([[10,30],
               [40,50]])
new_array=np.insert(array,1,[100,200], axis =None)
new_array

array([ 10, 100, 200,  30,  40,  50])

In [31]:
# .append() Adds number at the end of an array
a=np.array([1,2,3,4])
b=np.append(a,5)
b

array([1, 2, 3, 4, 5])

In [37]:
a=np.array([[1,2],
           [3,4]])
b = np.append(a, [[5, 6]], axis=0)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
# Appending as a new column → must match row count (2 rows)
b = np.append(a, [[5], [6]], axis=1)
print(b)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1